version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=exemplum
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=exemplum
    ports:
      - "5432:5432"
  db-shadow:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=exemplum
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=exemplum-shadow
    ports:
      - "5433:5432"
