-- AlterTable
ALTER TABLE "TodoItem" ADD COLUMN     "completedAt" TIMESTAMP(3);
ALTER TABLE "TodoItem" ALTER COLUMN "notes" DROP NOT NULL;
ALTER TABLE "TodoItem" ALTER COLUMN "reminder" DROP NOT NULL;
ALTER TABLE "TodoItem" ALTER COLUMN "dueDate" DROP NOT NULL;
ALTER TABLE "TodoItem" ALTER COLUMN "priorityLevel" DROP NOT NULL;
